pool: 'Azure Pipelines'

# variables:
# - group: temporaryvm

trigger:
  - main

steps:
- task: Docker@2
  displayName: Build and Push to Docker Container Registry
  inputs:
    containerRegistry: 'Docker Hub'
    repository: rdvansloten/deep-cut-bot
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    addPipelineData: false
    tags: |
      $(Build.BuildId)
      latest

# - task: InstallSSHKey@0
#   inputs:
#    knownHostsEntry: $(vmkhentry)
#    sshPublicKey: $(vmpubkey)
#    sshKeySecureFile: temporaryvm_pvkey

- task: SSH@0
  inputs:
    sshEndpoint: 'TemporaryVM'
    runOptions: 'inline'
    inline: |
      sudo docker rm -vf $(docker ps -aq) && docker rmi -f $(docker images -aq);
      sudo docker run --name deepcutbot -d --env-file discord-token.txt rdvansloten/deep-cut-bot:latest
    readyTimeout: '20000'
