pool: 'Azure Pipelines'

variables:
- name: app
  value: woomies-account-prod 
- name: rg
  value: woomies-resources-prod

trigger:
  - main

steps:
- task: Docker@2
  displayName: Build and Push to Docker Container Registry
  inputs:
    containerRegistry: 'Docker Hub'
    repository: rdvansloten/deep-cut-bot
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 
    - '$(Build.BuildId)'
    - 'latest'