apiVersion: apps/v1
kind: Deployment
metadata:
  name: deep-cut-bot
  labels:
    role: discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      role: discord-bot
  template:
    metadata:
      labels:
        role: discord-bot
    spec:
      containers:
        - name: bot
          image: rdvansloten/deep-cut-bot:latest
          env: 
          - name: DISCORD_TOKEN 
            valueFrom: 
              secretKeyRef: 
                name: deep-cut-bot-secret 
                key: discordtoken
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: deep-cut-bot-secret
                key: mysqlrootpassword
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: deep-cut-bot-secret
                key: mysqldatabase
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: deep-cut-bot-secret
                key: mysqluser
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: deep-cut-bot-secret
                key: mysqlpassword
        - name: database
          image: mysql:5.7-debian
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: deep-cut-bot-secret
                key: mysqlrootpassword
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: deep-cut-bot-secret
                key: mysqldatabase
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: deep-cut-bot-secret
                key: mysqluser
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: deep-cut-bot-secret
                key: mysqlpassword
