apiVersion: v1
kind: Pod
metadata:
  name: deep-cut-bot
  labels:
    role: discord-bot
spec:
  containers:
    - name: deep-cut-bot
      image: rdvansloten:deep-cut-bot:latest
      env: 
      - name: DISCORD_TOKEN 
        valueFrom: 
          secretKeyRef: 
            name: deep-cut-bot-secret 
            key: discordtoken 